version: "3.3"
services:
  blog-manu:
    image: manudiv1/manudiv-blog:alpine
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.blog-manu.entrypoints=websecure"
      - "traefik.http.routers.blog-manu.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.blog-manu.service=blog-manu"
      - "traefik.http.services.blog-manu.loadbalancer.server.port=${APP_PORT}"
volumes:
  code:
    driver: local

networks:
  proxy:
    external: true