name: ci

on:
  push:
    branches:
      - main

jobs:
  multi:
    runs-on: ubuntu-latest
    env: 
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/manudiv-blog

    steps:
      - uses: actions/checkout@v2
      
      - name: Creating envs
        run: |
          echo "IMAGE_TAG=sha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ env.DOCKER_IMAGE}}:latest,${{ env.DOCKER_IMAGE}}:${{ env.IMAGE_TAG }}

      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: 'blog-manudiv'
          stack-definition: 'infra.yml'
          image: ${{ env.DOCKER_IMAGE}}:${{ env.IMAGE_TAG }}
