name: ci

on:
  push:
    branches:
      - main
      - develop

jobs:
  multi:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/manudiv-blog
      URL: manudiv.org
      STACK-NAME: blog-manudiv

    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Select Env
        shell: bash
        run: |
          if [${steps.extract_branch.outputs.branch} = 'master'];
          then
            echo "##[set-output name=environment;]$(echo "production")"
            echo "##[set-output name=environment-folder;]$(echo "")"
            echo "##[set-output name=environment-url;]$(echo "${env.URL}")"
          elseif [${steps.extract_branch.outputs.branch} = 'develop']
            echo "##[set-output name=environment;]$(echo "staging")"
            echo "##[set-output name=environment-folder;]$(echo "development")"
            echo "##[set-output name=environment-url;]$(echo "dev.${env.URL}")"
          fi
        id: selection_environment

      - name: Creating envs
        run: |
          echo "IMAGE_TAG=sha-$(git rev-parse --short HEAD)-${{ steps.selection_environment.outputs.environment }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          build-args: ENVIRONMENT=${{ steps.selection_environment.outputs.environment-folder }}
          tags: ${{ env.DOCKER_IMAGE }}:latest,${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}

      - name: deploy to portainer
        uses: LGinC/portainer-stack-deploy@master
        with:
          serverurl: http://xxx.com:9000
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          endpointId: 1
          stackname: dotnet_test
          registry: mcr.microsoft.com
          imagename: dotnet/core/aspnet:3.1-alpine
          docker_compose: |
            version: "3.3"
            services:
              ${{ steps.selection_environment.outputs.environment }}-blog-manu:
                image: manudiv1/manudiv-blog:alpine
                restart: unless-stopped
                networks:
                  - proxy
                labels:
                  - "traefik.enable=true"
                  - "traefik.docker.network=proxy"
                  - "traefik.http.routers.${{ steps.selection_environment.outputs.environment }}-blog-manu.entrypoints=websecure"
                  - "traefik.http.routers.${{ steps.selection_environment.outputs.environment }}-blog-manu.rule=Host(`${{ steps.selection_environment.outputs.environment-url }}`)"
                  - "traefik.http.routers.${{ steps.selection_environment.outputs.environment }}-blog-manu.service=blog-manu"
                  - "traefik.http.services.${{ steps.selection_environment.outputs.environment }}-blog-manu.loadbalancer.server.port=80"
            networks:
              proxy:
                external: true

      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: ${{ steps.selection_environment.outputs.environment }}-${{ env.STACK-NAME }}
          stack-definition: "infra.yml"
          image: ${{ env.DOCKER_IMAGE}}:${{ env.IMAGE_TAG }}
